---
name: Comment on PR
author: Alexander Hirdman
description: Create a comment on a pull request

runs:
  using: node20
  main: ../build/comment/index.js
inputs:
  github-token:
    description: Authorized github-token
    required: true
  message:
    description: Message to be sent in comment
    required: true
outputs:
  result:
    description: Sample result for now
