---
name: Comment on PR
author: Alexander Hirdman
description: Create a comment on a pull request

runs:
  using: node20
  main: ../build/comment/index.js
inputs:
  github-token:
    description: Authorized github-token
    required: true
  message:
    description: Message to be sent in comment
    required: false
  comment-id:
    description: Optional comment identifier. If supplied and found in subsequentent workflows, previous comment will be overwritten
    required: false
  template:
    description: Optional pre-defined comment template, can be "none" or "fingerprint". Defaults to "none"
    required: false
    default: "none"
  fingerprint-diff:
    description: Used with a "fingerprint" - template to pretty print fingerprint JSON output
    required: false
  delete-old:
    description: Optional boolean to delete a previously created comment. Requires a "comment-id"
    required: false
    default: "false"
outputs:
  result:
    description: Sample result for now
