---
name: Comment on PR
author: Alexander Hirdman
description: Create a comment on a pull request

runs:
  using: node20
  main: ../build/comment/index.js
inputs:
  github-token:
    description: Authorized github-token
    required: true
  message:
    description: Message to be sent in comment
    required: false
  template:
    description: Optional pre-defined comment template, can be "none" or "fingerprint"
    required: false
  fingerprint-diff:
    description: Used with a "fingerprint" - template to pretty print fingerprint JSON output
    required: false
outputs:
  result:
    description: Sample result for now
