name: Say hello 👋

on: pull_request

permissions:
  issues: write
  pull-requests: write

jobs:
  create-a-comment:
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Check out Git repository
        uses: actions/checkout@v4

      - name: Say hello
        uses: ./comment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            {"sources":[{"type":"file","filePath":"./assets/icons/app_icon.png","reasons":["expoConfigExternalFile"],"hash":"3b99ece8c252fdbaa3175957c9688c06c51e4271"},{"type":"file","filePath":"./assets/images/splash.png","reasons":["expoConfigExternalFile"],"hash":"206a875d5dc6f23eb9515bebd899ebb9f56eca82"},{"type":"file","filePath":".gitignore","reasons":["bareGitIgnore"],"hash":"9e8fed2a6ad3c362967831f003ae148407897504"}],"hash":"5730ef1e3090a76985182a36b916761d69b5953c"}
