name: Say hello 👋

on: pull_request

permissions:
  issues: write
  pull-requests: write

jobs:
  create-a-comment:
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Check out Git repository
        uses: actions/checkout@v4

      - name: Fingerprint template
        uses: ./comment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: fingerprint-template
          template: fingerprint
          fingerprint-diff: |
            {"sources":[{"type":"file","filePath":"./assets/icons/app_icon.png","reasons":["expoConfigExternalFile"],"hash":"3b99ece8c252fdbaa3175957c9688c06c51e4271"},{"type":"file","filePath":"./assets/images/splash.png","reasons":["expoConfigExternalFile"],"hash":"206a875d5dc6f23eb9515bebd899ebb9f56eca82"},{"type":"file","filePath":".gitignore","reasons":["bareGitIgnore"],"hash":"9e8fed2a6ad3c362967831f003ae148407897504"}],"hash":"5730ef1e3090a76985182a36b916761d69b5953c"}

      - name: Regular comment
        uses: ./comment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: regular-comment
          delete-old: true
          message: |
            The Pull Request introduced fingerprint changes against the base commit:
            <details><summary>Fingerprint diff</summary>

            ```json
            { "hello": "mars" }
            ```

            </details>

            ---
            *Generated by [PR labeler](https://github.com/expo/expo/actions/workflows/pr-labeler.yml) 🤖*
